Added punctuation to About Us Spanish Heading
playfulprogramming/playfulprogramming pull request #1130
Opened 2024-08-21 22:44 UTC by ThorondorManwe

A little change in a Heading to add a question mark at the start

2024-08-21 22:45 UTC, crutchcorn approved these changes
Congrats on the first PR!!!! Thank you for helping us with the change :) Look forward to working more together

2024-08-22 18:49 UTC, ThorondorManwe commented
Thanks so much! It will be great to contribute to this awesome project!

2024-08-25 20:52 UTC, jahirfiquitiva requested changes

2024-08-25 20:52 UTC, jahirfiquitiva commented on CONTRIBUTING.es.md
> +Como comunidad le damos la bienvenida a cualquiera que desee escribir y enviar entradas al blog de Playful Programming. ¡Vamos! En este documento revisaremos los pasos necesarios para crear una nueva
I suggest to not add text that was not present in the original one.

```suggestion
Como comunidad le damos la bienvenida a cualquiera que desee escribir y enviar entradas al blog de Playful Programming. En este documento revisaremos los pasos necesarios para crear una nueva publicación, y después enviarla a PP como una *pull request* o solicitud para incorporar cambios.
```

2024-08-25 20:52 UTC, jahirfiquitiva commented on CONTRIBUTING.es.md
> +> [!NOTA]
While this translation is correct, it will likely break GitHub's custom rendering for this block

```suggestion
> [!NOTE]
```

2024-08-25 20:52 UTC, jahirfiquitiva commented on CONTRIBUTING.es.md
> +> Para un tutorial más general sobre cómo contribuir a un proyecto con GitHub podrías revisar la guía [ Primeras contribuciones](https://github.com/firstcontributions/first-contributions/blob/main/tr
```suggestion
> Para un tutorial más general sobre cómo contribuir a un proyecto con GitHub podrías revisar la guía ["Primeras contribuciones"](https://github.com/firstcontributions/first-contributions/blob/main/translations/README.mx.md) antes de seguir leyendo esta página.
```

2024-08-25 20:52 UTC, jahirfiquitiva commented on CONTRIBUTING.es.md
> +2. [Escribir una nueva entrada](#escribir-una-nueva-entrada)
I think "publicación" is a better translation for "post". I'd suggest updating all occurrences

```suggestion
2. [Escribir una nueva publicación](#escribir-una-nueva-publicación)
```

2024-08-25 20:52 UTC, jahirfiquitiva commented on CONTRIBUTING.es.md
> +Antes de crear una nueva entrada, deberás añadir información acerca de ti. Para lograr eso, crea una nueva carpeta en [`content/`](./content/) con tu nombre de usuario, y agrega un archivo `index.md`
```suggestion
Antes de crear una nueva publicación, deberás añadir información acerca de ti. Para lograr eso, crea una nueva carpeta en [`content/`](./content/) con tu nombre de usuario, y agrega un archivo `index.md` dentro de ésta; por ejemplo: `content/eric/index.md`.
```

2024-08-25 20:52 UTC, jahirfiquitiva commented on CONTRIBUTING.es.md
> +  // "description" es una biografá corta que se mostrará en tu página de perfil
```suggestion
  // "description" es una biografia corta que se mostrará en tu página de perfil
```

2024-08-25 20:52 UTC, jahirfiquitiva commented on CONTRIBUTING.es.md
> +  // que se vea en tus entradas
```suggestion
  // que se vea en tus publicaciones
```

2024-08-25 20:52 UTC, jahirfiquitiva commented on CONTRIBUTING.es.md
> +  // y "cohost", además de un "website" ¡Puede ser lo que quieras!
```suggestion
  // y "cohost", además de un "website" que puede ser lo que quieras!
```

2024-08-25 20:52 UTC, jahirfiquitiva commented on CONTRIBUTING.es.md
> +>¿No quieres mostrar tu foto real en el sitio? ¡Está bien! Tenemos [bastantes emoticones de unicornio personalizados que puedes usar como imagen de perfil](https://github.com/playfulprogramming/desig
```suggestion
> ¿No quieres mostrar tu foto real en el sitio? ¡Está bien! Tenemos [bastantes emoticones de unicornio personalizados que puedes usar como imagen de perfil](https://github.com/playfulprogramming/design-assets/tree/main/emotes). ¡Son adorables, ve a verlos! 🤩
```

2024-08-25 20:52 UTC, jahirfiquitiva commented on CONTRIBUTING.es.md
> +> **¿Estás familiarizado/a con Markdown?**
```suggestion
> **¿Eres nuevo con Markdown?**
```

2024-08-25 20:52 UTC, jahirfiquitiva commented on CONTRIBUTING.es.md
> +> ¿Revisa el documento [Markdown Cheatsheet](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet) para ver ejemplos de cómo formatear distintos tipos de contenido en este archivo!
```suggestion
> ¿Revisa el documento [Markdown Cheatsheet](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet) para ver ejemplos de cómo dar formato a distintos tipos de contenido en este archivo!
```

2024-08-25 20:52 UTC, jahirfiquitiva commented on CONTRIBUTING.es.md
> +  description: "¡Ésta es mi primera entrada en el sitio de Playful Programming!",
```suggestion
  title: "Mi primera publicación en el blog",
  description: "¡Ésta es mi primera publicación en el sitio de Playful Programming!",
```

2024-08-25 20:52 UTC, jahirfiquitiva commented on CONTRIBUTING.es.md
> +  Existen algunas propiedades extra que *podrías* incluir en el frontmatter de tu entrada, pero no son necesarias:
```suggestion
  Existen algunas propiedades extra que *podrías* incluir en el frontmatter de tu entrada, pero que no son necesarias:
```

2024-08-25 20:52 UTC, jahirfiquitiva commented on CONTRIBUTING.es.md
> +  - `authors: ["autor1", "autor2"]` se puede usar para especificar de forma manual los ID's de los autores de una entrada, esto cuando la publicación tenga más de un autor.
```suggestion
  - `authors: ["autor1", "autor2"]` se puede usar para especificar de forma manual los ID's de los autores de una entrada en caso de que la publicación tenga varios autores.
```

2024-08-25 20:52 UTC, jahirfiquitiva commented on CONTRIBUTING.es.md
> +  - `edited: "2023-10-21"` sirve para especificar la fecha en la hiciste la "última actuaización" de tu entrada en caso de que realices modificaciones.
```suggestion
  - `edited: "2023-10-21"` sirve para especificar la fecha en la que hiciste la "última actualización" de tu entrada en caso de que realices modificaciones.
```

2024-08-25 20:52 UTC, jahirfiquitiva commented on CONTRIBUTING.es.md
> +  - `collection: "Mi genial serie de artículos"` tratará a un grupo de publicaciones como una serie en caso de que todas tengan la misma cadena `collection` configurada.
```suggestion
  - `collection: "Mi genial serie de artículos"` tratará a un grupo de publicaciones como una serie en caso de que todas tengan el mismo texto `collection` configurado.
```

2024-08-25 20:52 UTC, jahirfiquitiva commented on CONTRIBUTING.es.md
> +Proporcionar una licencia ayuda a explicar lo que los lectores pueden hacer con su trabajo - ya sea que puedan usarlo como material para un curso, o reusarlo en otras formas. Visita [el sitio de Crea
```suggestion
Proporcionar una licencia ayuda a explicar lo que los lectores pueden hacer con tu trabajo - ya sea que puedan usarlo como material para un curso, o reusarlo en otras formas. Visita [el sitio de Creative Commons](https://creativecommons.org/about/cclicenses/) para obtener una descripción general de lo que se permite hacer dentro de los distintos tipos de licencias.
```

2024-08-25 20:52 UTC, jahirfiquitiva commented on CONTRIBUTING.es.md
> +Las entradas pueden incristar sus propias etiquetas `<iframe>` si es necesario - éstas mostrarán una vista previa de "haz clic para ejecutar" y no afectarán el tiempo de carga de la página.
```suggestion
Las entradas pueden incrustar sus propias etiquetas `<iframe>` si es necesario - éstas mostrarán una vista previa de "haz clic para ejecutar" y no afectarán el tiempo de carga de la página.
```

2024-08-25 20:52 UTC, jahirfiquitiva commented on CONTRIBUTING.es.md
> +También puedes incrustar algunos servicios de terceros simplemente pegando el enlace en tu entrada, como vídeos de YouTube o de Twitch, publicaciones de Twitter - y cualquier cosas compatible con [oe
```suggestion
También puedes incrustar algunos servicios de terceros simplemente pegando el enlace en tu publicación, como videos de YouTube o de Twitch, publicaciones de Twitter - y cualquier opción soportada por [oembed.com](https://oembed.com).
```

2024-08-25 20:52 UTC, jahirfiquitiva commented on CONTRIBUTING.es.md
> +## Imágenes y vídeos
There's a "dilemma" here ... `vídeo` is used in Spain, while `video` is used in most of other Spanish-speaking countries 🤔 

```suggestion
## Imágenes y videos
```

2024-08-25 20:52 UTC, jahirfiquitiva commented on CONTRIBUTING.es.md
> +Si metiste enlaces a imágenes o vídeos necesitarás guardar esos archivos en la misma carpeta que tu entrada y cambiar tu documento markdown para que haga referencia a éstos de forma local:
```suggestion
Si añadiste enlaces a imágenes o videos, necesitarás guardar esos archivos en la misma carpeta que tu entrada y cambiar tu documento markdown para que haga referencia a éstos de forma local:
```

2024-08-25 20:52 UTC, jahirfiquitiva commented on CONTRIBUTING.es.md
> +# Traducir una entrada del blog
```suggestion
# Traducir una publicación del blog
```

2024-08-25 20:52 UTC, jahirfiquitiva commented on CONTRIBUTING.es.md
> +Para crear un archivo de traduccción para una entrada, copia su archivo `index.md` y renómbralo a `index.(lenguaje).md`, donde `(lenguaje)` es el lenguaje al que traduces la entrada. Por ejemplo, una
```suggestion
Para crear un archivo de traduccción para una publicación, copia su archivo `index.md` y renómbralo a `index.(lenguaje).md`, donde `(lenguaje)` es el idioma al que traduces la entrada. Por ejemplo, una traducción al `fr` (francés) podría ser nombrada `index.fr.md`. El contenido dentro de este archivo puede ser traducido a su idioma respectivo.
```

2024-08-25 20:52 UTC, jahirfiquitiva commented on CONTRIBUTING.es.md
> +> Si fuera necesario traducir cualquiera de las inágenes usadas en la entrada, éstas deberán ser nombradas de forma similar - por ejemplo, una traducción de `dom_tree.svg` deberá ser nombrada `dom_tr
```suggestion
> Si fuera necesario traducir cualquiera de las imágenes usadas en la entrada, estas deberán ser nombradas de forma similar - por ejemplo, una traducción de `dom_tree.svg` deberá ser nombrada `dom_tree.fr.svg`.
```

2024-08-25 20:52 UTC, jahirfiquitiva commented on CONTRIBUTING.es.md
> +Para una referencia de los códigos de cada lenguaje, puedes consultar el archivo [`/content/data/languages.json`](./content/data/languages.json) - si el lenguaje que quieres usar no se encuentra tal
```suggestion
Como referencia, los códigos de cada idioma los puedes consultar en el archivo [`/content/data/languages.json`](./content/data/languages.json) - si el idioma que quieres usar no se encuentra tal vez sea necesario que lo agregues.
```

2024-08-25 20:52 UTC, jahirfiquitiva commented on CONTRIBUTING.es.md
> +## Encontrar un código de lenguaje
```suggestion
## Encontrar un código de idioma
```

2024-08-25 20:52 UTC, jahirfiquitiva commented on CONTRIBUTING.es.md
> +Cada código de lenguaje dentro de [`/content/data/languages.json`](./content/data/languages.json) debería estar formado de dos letras en minúscula. Si incluye una región, agrega un guion seguido de o
```suggestion
Cada código de idioma dentro de [`/content/data/languages.json`](./content/data/languages.json) debería estar formado de dos letras en minúscula. Si incluye una región, agrega un guion seguido de otras dos letras en minúscula. Por ejemplo, el código para el francés es `fr` - para referirse al dialecto del francés que se habla en Canadá, el código será `fr-ca`.
```

2024-08-25 20:52 UTC, jahirfiquitiva commented on CONTRIBUTING.es.md
> +Una vez que hayas hecho todos los cambios, [crea una Pull Request](https://docs.github.com/es/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating
```suggestion
Una vez que hayas hecho todos los cambios, [crea una Pull Request](https://docs.github.com/es/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request) para agregar tu publicación al sitio.
```

2024-08-25 20:52 UTC, jahirfiquitiva commented on CONTRIBUTING.es.md
> +- Una vez combinada (*merged*), ¡Tu entrada será visible en el sitio!
```suggestion
- Una vez combinada (*merged*), ¡tu entrada será visible en el sitio!
```

2024-08-25 20:52 UTC, jahirfiquitiva commented on CONTRIBUTING.es.md
> +- Revisa que todos tus archivos estén dentro de la Pull Request, y que éstos estén siendo combinados dentro de la rama principal o `main`.
```suggestion
- Revisa que todos tus archivos estén dentro de la Pull Request, y que estos estén siendo combinados a la rama principal o `main`.
```

2024-08-27 18:13 UTC, hamirmahal commented on content/carlosrangel-dev/index.md
> +	description: "Carlos is a FrontEnd developer that visits BackEnd world occasionally. 🤖\nHe is starting his adventure with code and looking to contribute to interesting projects and connect with peop
```suggestion
	description: "Carlos is a FrontEnd developer who visits the BackEnd world occasionally. 🤖\nHe is starting his adventure with code and looking to contribute to interesting projects and connect with people through coding and books. 🧙‍♂️\nHe likes to write for his blog, write short fiction, code, and spend time with his family.",
```

2024-09-01 00:47 UTC, jahirfiquitiva approved these changes

2024-09-01 21:35 UTC, merged